apiVersion: apps/v1
kind: Deployment
metadata:
  name: communication-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: communication
  template:
    metadata:
      labels:
        app: communication
    spec:
      containers:
        - name: communication
          image: vaibhavgera/communication
          env:
            - name: MONGO_URI
              value: "mongodb://orders-mongo-srv:27017/orders"
            - name: REDIS_HOST
              value: communication-redis-srv
